### PR TITLE
fix #412: adds check for blog post type.

### LINKED ISSUE #412: UI tests failing for blog posts which are not release related
We have blog posts which are not relese-related, eg #410. However our test suite verifies if each and every blog post has release notes, regardless of its type. This results in errors such as

```
Missing release notes for blog post titled: End-To-End Integration Testing For Kubernetes/OpenShift.
```

### Proposed solution

Before doing a release notes verification check if the blog post is an actual release post. This can be done by checking if it was tagged with `release`, e.g.

image

### PR DESCRIPTION
**Pull request by hemanik**
#### Short description of what this resolves:
Ignores release notes validations for blog post that are of non-release type.

#### Changes proposed in this pull request:

- Adds check for blog-post type before validating presence of release-notes.

**Fixes**: #412

### CODE REVIEW

File: src/test/java/org/arquillian/tests/pagetests/BlogPageTest.java [hunk 1]
```diff
@@ -92,4 +92,17 @@ public void should_redirect_to_new_announcement_if_banner_is_present() throws Ex
...
+    public void should_ignore_release_notes_for_non_release_blog_posts() throws Exception {
+        mainPage.menu()
+                .navigate().to("Blog");
+
+        blogPage.cloudTag()
+                .navigate().to("nonrelease");
+
+        blogPage.blogContent()
+                .verify()
+                .hasReleaseNotes();
```
Comment (bartoszmajsak) [inline src/test/java/org/arquillian/tests/pagetests/BlogPageTest.java]: I don't understand the flow of this test

- we navigate to Blog
- we navigate to non-release (I guess we click on the tag)
   - this leads us to a page with several blogs
- we check if the content has release notes then (content of what?)

Comment (bartoszmajsak) [reply src/test/java/org/arquillian/tests/pagetests/BlogPageTest.java]: I was hoping that you can propose some improvement in this code :)

File: src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java [hunk 2]
```diff
@@ -22,7 +22,11 @@
     @FindBy(css = "[class = 'tag-cloud']")
     private CloudTagFragment cloudTag;
 
-    public BlogFragment blogContent() {
+    public BlogFragment releaseBlog() {
+        return blogContent;
+    }
+
+    public BlogFragment nonReleaseBlog() {
         return blogContent;
```
Comment (bartoszmajsak) [inline src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: I don't understand why we have two methods returning the same object. I think the original problem I was suggesting to fix was that on the page were we have multiple blogs calling `blogContent` method will led to the first blog, but that was not obvious from the test itself.

File: src/test/java/org/arquillian/tests/pagetests/BlogPageTest.java [hunk 3]
```diff
@@ -81,15 +81,28 @@ public void should_redirect_to_new_announcement_if_banner_is_present() throws Ex
...
+                .hasAnnouncementBanner(true);
 
         blogPage.newAnnouncementBanner()
             .navigate().to("Check our latest announcement");
 
-        blogPage.blogContent()
+        blogPage.releaseBlog()
             .verify()
-            .hasAnnouncementBanner(false);
+                .hasAnnouncementBanner(false);
```
Comment (bartoszmajsak) [inline src/test/java/org/arquillian/tests/pagetests/BlogPageTest.java]: How about `.hasAnnouncementBanner()` and `.doesNotHaveAnnouncementBanner()` instead?

File: src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java (hunk 2 above)
Comment (hemanik) [reply src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: I am confused. We check for all the blogs on the blog page and not just the first blog.

Comment (bartoszmajsak) [reply src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: If that is the case, then we have to rework the structure of page objects we have in place. Not sure if `BlogFragment` should represent more than one blog entry.

Comment (hemanik) [reply src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: That makes sense but then don't we check for all the release blogs for release notes or just the first one ?

Comment (bartoszmajsak) [reply src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: We can always check for all, just "reverse" the logic for it somehow. We anyway never check all, but first `n` displayed, right?

Comment (bartoszmajsak) [reply src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: As this page is changing over the time I am not sure the test as we have now is really what we want. I would rather think of having two separated test cases.

1. Go to "release" posts and check for release notes in all displayed on the first page, because in there we know that we should have release notes. (plus title and author)

2. Go to "non-release" blog posts and check if title and author are there?

Comment (hemanik) [reply src/test/java/org/arquillian/tests/pom/pageObjects/BlogPage.java]: > I would rather think of having two separated test cases.

> Go to "release" posts and check for release notes in all displayed on the first page, because in there we know that we should have release notes. (plus title and author)

> Go to "non-release" blog posts and check if title and author are there?

That's what I tried doing here, may be some more refactoring should help.
